### ISSUE TITLE
IFR Below Utica Res

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#12]
I think some simplification has been done in this area.  Currently, the adjacent USGS gauge node to this IFR node is 11203600.  In reality, two things happen between "Below Utica Reservoir" and 11203600, according to the USGS schematic: Silver Creek joins NFSR, Water exits NSFR through North Fork Stanislaus River Diversion Tunnel.  If you are looking for a more accurate reference hydrograph for the location of this IFR, please use USGS gauge 11293372.

**Comment by rheinheimer** [comment]
Thanks @alanccai. I moved the IFR below Utica and added the USGS gauge, for which we don't have data yet. The rest of the schematic looks okay. Note again distances don't actually matter from a modeling perspective. This issue is resolved.

![image](https://user-images.githubusercontent.com/9124277/68722627-ad9bb300-057b-11ea-92c7-bbc2d2b3f4ad.png)
