### ISSUE TITLE
IFR bl Donnells Reservoir location

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#13]
I think the Streamflow Gauge node for 11292700 has been misplaced.  It should be above the outflow from Donnell PP, not below it.  11292700 and the IFR node should be adjacent.  The IFR node looks correctly placed, "at or immediately downstream of Donnells Dam" as the license says.

**Comment by alanccai** [comment]
See https://ca.water.usgs.gov/data/waterdata/Schematics2010/stanislaus.r.basin.pdf

**Comment by asood12** [comment]
Supplemental flow requirement:
For years in which Donnells Reservoir is forecasted not to spill, the Licensee shall initiate the 13-week-long Supplemental Flow period at atime between March 1 and May 1 so that the peak Supplemental Flow will occur approximately two weeks after the forecasted peak inflow to Donnells Reservoir (Peak Flow Trigger). The schedule is as follows:

Week | Supp flow (cfs)
1 | 5
2 | 10
3 | 25
4 | 35
5 | 75
6 | 125
7 | 200
8 | 325
9 | 175
10 | 95
11 | 55
12 | 25
13 | 10
The peak flow date for Livneh has been calculated in the file - peak_runoff_DonnellsRes_MarToMay_cms.csv

**Comment by rheinheimer** [comment]
See also #61

**Comment by rheinheimer** [comment]
Schematic is fixed.

**Comment by GustavoFacincani** [comment]
Comparing the text to the pseudocode I just found this difference, although I think it's probably insignificant: For WYT classification according to the unimpaired inflow: Dry = only greater than 350,000 (not greater or equal). Normal = only greater than 676,000 (not greater or equal).
