### ISSUE TITLE
Below Warm Creek Diversion

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#27]
Warm Creek is not a part of the network. The schematic says it's a tributary of the SFSJR

See: https://ca.water.usgs.gov/data/waterdata/Schematics2010/s.joaquin.up.r.basin.pdf

**Comment by rheinheimer** [comment]
This is interesting. I'm not sure why it wasn't originally included (there is a long, 10+ year history with the catchment definitions). Here's my own interpretation of how this would look. I think this will be either a perpetually open issue, or one that we definitely close. The rational for not including Warm Creek is that the volume is probably well within the noise of model uncertainty.

![image](https://user-images.githubusercontent.com/9124277/68734013-53601980-059e-11ea-8cce-47abdc685660.png)

**Comment by alanccai** [comment]
Your schematic looks good.  

I think you may be right about "Within the noise of model uncertainty"

![image](https://user-images.githubusercontent.com/35709110/68737768-51478c00-0599-11ea-9315-6fadc98f485d.png)

**Comment by rheinheimer** [comment]
Actually, we're good, and already include Warm Creek: the gauge (and diversion) are already in the TAE subwatershed, so **all** of that flow above the diversion are already going into TAE. So actually we have the opposite problem: none of that upper Warm Creek water flows into the SF San Joaquin. However, since this is typically less than 0.5 cfs, this is not going to significantly affect the model.
